Feat/#15 set order mass
Poukam-Pierre/EasyMass pull request #16
Opened 2024-06-10 16:05 UTC by Poukam-Pierre

2024-06-13 11:45 UTC, Tchakoumi requested changes

2024-06-13 11:45 UTC, Tchakoumi commented on apps/easy-messe/components/OfferMass/LetOfferMass.tsx
> +            <Typography variant="h2">{formatMessage({ id: 'ApplicantInformation' })}</Typography>
```suggestion
            <Typography variant="h2">{formatMessage({ id: 'applicantInformation' })}</Typography>
```

these data should be in camelCase

2024-06-13 11:45 UTC, Tchakoumi commented on apps/easy-messe/components/OfferMass/LetOfferMass.tsx
> +                            onChange={(_) => setIsAnonym(_.target.checked)}
```suggestion
                            onChange={(event) => setIsAnonym(event.target.checked)}
```

2024-06-13 11:45 UTC, Tchakoumi commented on apps/easy-messe/components/OfferMass/LetOfferMass.tsx
> +            <Typography variant="h2">{formatMessage({ id: 'MassInformations' })}</Typography>
```suggestion
            <Typography variant="h2">{formatMessage({ id: 'massInformations' })}</Typography>
```

2024-06-13 11:45 UTC, Tchakoumi commented on apps/easy-messe/components/OfferMass/LetOfferMass.tsx
verify all your formatMessage texts and make them in camelCase.

2024-06-16 18:42 UTC, Poukam-Pierre commented on apps/easy-messe/components/OfferMass/LetOfferMass.tsx
> +    const massLoop: MassGroupCategory[] = [
Here is different kind of mass group. In simple click, we can offer a group of masses througth the calendar on specific church.

2024-06-16 18:43 UTC, Poukam-Pierre commented on apps/easy-messe/components/OfferMass/LetOfferMass.tsx
> +    const massLoop: MassGroupCategory[] = [
I've changed massLoop by massOrderCategory

2024-06-16 18:49 UTC, Poukam-Pierre commented on apps/easy-messe/components/OfferMass/DateTimeMass/DateTimeMass.tsx
> +        <LocalizationProvider dateAdapter={AdapterDayjs} adapterLocale={activeLanguage}>
It's only appear in this part of app.  But we'll also use that on admin App. As a monoripo project is there good to still send this provider at the root?

2024-06-16 18:59 UTC, Poukam-Pierre commented on apps/easy-messe/components/OfferMass/DateTimeMass/DateTimeMass.tsx
> +}) {
![review0](https://github.com/Poukam-Pierre/EasyMass/assets/69717653/24f987e7-c537-4125-86ec-b7553fe81a66)
There is a problem when put the type straight in. Can you show me the way?

2024-06-24 16:42 UTC, Tchakoumi commented on apps/easy-messe/components/OfferMass/DateTimeMass/DateTimeMass.tsx
> +}) {
It should work.
verify what attributes exist in the ParishData and use it.

you cannot try to destructure `parishData` from `ParishData`, it does not make sense

2024-06-25 15:03 UTC, Poukam-Pierre commented on apps/easy-messe/components/OfferMass/DateTimeMass/DateTimeMass.tsx
> +}) {
yes it's true. haha..

2024-06-25 15:13 UTC, Poukam-Pierre commented on apps/easy-messe/components/OfferMass/DateTimeMass/DateTimeMass.tsx
> +        <LocalizationProvider dateAdapter={AdapterDayjs} adapterLocale={activeLanguage}>
Okey

2024-06-26 21:18 UTC, Tchakoumi requested changes

2024-06-26 21:18 UTC, Tchakoumi commented on apps/easy-messe/pages/offer-mass/index.tsx
> +                    } */}
remove commented code before requesting for a review.

commented code shouldn't go to prod

2024-06-26 21:18 UTC, Tchakoumi commented on apps/easy-messe/components/OfferMass/DateTimeMass/TimeClock.tsx
> +            ampm={activeLanguage === 'fr' ? false : true}
the condition already returns true or false.

```suggestion
            ampm={activeLanguage === 'fr'}
```

2024-06-26 21:18 UTC, Tchakoumi commented on apps/easy-messe/components/OfferMass/OfferMassCard.tsx
> +                            {mass.massInfos.price !== null && `${mass.massInfos.price} frs CFA`}
you don't need to present the number with ~frs CFA~
`formatNumber` from `react-intl` does that for you and automatically formats the number with spaces or commas, and adds the appropriate currency.

```ts
formatNumber(mass.massInfos.price, {style: 'currency', currency: 'XAF'})
```

destructure the mass object at the top of the file.

to check for `null` or `undefine` or `empty string` or `0`, you don't need to precise those, unless you need that specific check.


```suggestion
                            {mass.massInfos.price && formatNumber(mass.massInfos.price, {style: 'currency', currency: 'XAF'})}
```

2024-06-27 10:44 UTC, Poukam-Pierre commented on libs/theme/src/offerMasses/offerMass.interface.ts
>  }
All right!

2024-07-05 11:13 UTC, Poukam-Pierre commented on apps/easy-messe/components/OfferMass/OfferList.tsx
> +                    disabled={massRequested.length === 0 ? true : false}
This test get true or false. Don't need to specify like that. 
```suggestion
                    disabled={massRequested.length === 0 }
```

2024-07-05 11:15 UTC, Poukam-Pierre commented on apps/easy-messe/components/OfferMass/OfferList.tsx
> +                        display: massRequested.length === 0 ? 'none' : 'inherit'
This has been notify above. Don't need repete the result.

2024-07-05 11:35 UTC, Poukam-Pierre commented on apps/easy-messe/components/layout/Header/Header.tsx
> +                        onClick={() => openSideBar()}
Don't need arrow function here just call it.

2024-07-05 11:36 UTC, Poukam-Pierre commented on apps/easy-messe/components/layout/Header/SideBar/SideBar.tsx
> +            onClose={() => onClose()}
Don't need arrow function here. Just call it.

2024-07-05 11:41 UTC, Poukam-Pierre commented on libs/theme/src/offerMasses/offerMass.interface.ts
> +interface Requester {
restructure requester's data here to make it either a person nor anonymous not having both at the same type.

2024-07-05 11:42 UTC, Poukam-Pierre commented on libs/utils/src/lib/utils.ts
> +export function formattedDateTime(dateTime: Dayjs): string {
consider language when figure out the format date and time.

2024-07-05 12:11 UTC, Poukam-Pierre reviewed
breack all changes and push before merge.
Thanks!

2024-07-05 12:17 UTC, merged