Feat/#43 set up database
Poukam-Pierre/EasyMass pull request #45
Opened 2024-08-16 20:02 UTC by Poukam-Pierre

2024-08-16 22:12 UTC, Marcjazz requested changes
Why is your CI failing ?

2024-08-16 22:12 UTC, Marcjazz commented on apps/backend/src/app/database/database.module.ts
Generally, I will name this module `PrismaModule` and move it to the prisma folder to keep it simple. It's all advisable to make the module global so that you will only have to import it once in the `AppModule` and all children modules of the App will be able to consume it without you necessarily importing it.

2024-08-29 10:42 UTC, Poukam-Pierre reviewed
All is done!

2024-08-29 10:42 UTC, Poukam-Pierre commented on apps/backend/src/app/database/database.module.ts
okey I will replace.
I don't really know why my CI fails. Since Front-End project, it does like that.

2024-08-29 10:42 UTC, Poukam-Pierre commented on apps/backend/src/app/database/database.module.ts
I'm facing a problem with the architecture of project. My database folder is within the src folder while the prisma file is out of src. Replacing my database out of src will still work? Is it like that prisma module going to be global?

2024-08-29 10:42 UTC, merged