Feat/#5 set header
Poukam-Pierre/EasyMass pull request #8
Opened 2024-05-06 13:34 UTC by Poukam-Pierre

2024-05-06 14:34 UTC, Poukam-Pierre commented on apps/easy-messe/components/layout/Header/Header.tsx
> +                padding: { laptop: '16px, 90px', mobile: '13px 21px' }
```suggestion
                padding: { laptop: '16px 90px', mobile: '13px 21px' }
```

2024-05-28 09:04 UTC, Tchakoumi requested changes

2024-05-28 09:04 UTC, Tchakoumi commented on apps/easy-messe/pages/_app.tsx
> +                    <title>{"Let's Order a Mass Remotly - EasyMesse"}</title>
type: Remotely

```suggestion
                    <title>{"Order masses remotely - EasyMesse"}</title>
```

2024-05-28 09:04 UTC, Tchakoumi commented on libs/theme/src/languages/fr/website.ts
> +  orderMass: 'Offrir une messe',
is order mass `demander une messe` or ~offrir une messe~?

2024-05-29 13:11 UTC, merged